print("Hello, World!")
print("... umm 'hi'")
print('How\'s it going?')
print('whoa, single quotes too?')
print("Yes.", end =" ")
print("Either are fine to use.")
print("How did you..")
print()
print("\"put two prints on one line\"?")
print('what is the "\\" character for?')
print("To get \" characters in the output.")
print("Python won't consider it as ending a string.")
print('You can also use the other " character.')
