print("When including quotes, \" or ' in output.. \nyou must use the escape character '\\'")
print()
print("If you want to use '\\' in output,\nyou need to escape the escape character..\ne.g., \\\\")
print()
print("\"\"\\_('>')_/\"\"")
