name = input("Hello.  What is your name? ")
print()
age = int(input(f"Hi, {name}!  How old are you? "))
print()
print("Did you know that in five years you will be", age + 5, "years old?")
print(f"And five years ago you were {age - 5}!  Imagine that!")