number1 = float(input("What is your first number? "))
number2 = float(input("What is your second number? "))
number3 = float(input("What is your third number? "))
print()
print(f"({number1} + {number2} + {number3}) / 2 is {(number1 + number2 + number3) / 2}")